name: sophiread_unittest

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - qa
      - next
    tags:
      - "v*"

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.13.0
      - name: Install dependencies
        run: pixi install
      - name: Build and test
        run: |
          pixi run build
          pixi run test

  macos-latest:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.13.0
      - name: Install dependencies
        run: pixi install
      - name: Build and test
        run: |
          pixi run build
          pixi run test
