name: sophiread_unittest

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - qa
      - next
    tags:
      - "v*"

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sophiread
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v0.41.4
          manifest-path: sophiread/pixi.toml
      - name: Build and test
        run: |
          pixi run build
          pixi run test

  macos-latest:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: sophiread
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v0.41.4
          manifest-path: sophiread/pixi.toml
      - name: Build and test
        run: |
          pixi run build
          pixi run test
