name: sophiread_unittest

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - qa
      - next
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sophiread
    steps:
      - uses: actions/checkout@v6
      - uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
        with:
          manifest-path: sophiread/pixi.toml
      - name: Build and test
        run: |
          pixi run build
          pixi run test

  macos-latest:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: sophiread
    steps:
      - uses: actions/checkout@v6
      - uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
        with:
          manifest-path: sophiread/pixi.toml
      - name: Build and test
        run: |
          pixi run build
          pixi run test
